### ISSUE TITLE
Error while extracting OCT images from E2E format

### ISSUE THREAD

**Issue by NK-qub** [marksgraham/OCT-Converter#53]
Thank you for developing this tool. I am using it to convert .e2e format to extract oct images.  I have almost 1000 files in .e2e format and trying to extract the oct images from it. However for some of the files it correctly extract the oct images but for few files it gives the following two different errors while extracting oct images. These both errors are for two different .e2e files.
1. cannot reshape array of size 366807 into shape (768,768)
2. 'int' object has no attribute 'shape'
I have also attached both the errors.
Thanks you!.
<img width="751" alt="error1" src="https://user-images.githubusercontent.com/97097930/163165778-57968ac6-8f4d-4f36-9659-304611b2b6a9.png">
<img width="778" alt="error2" src="https://user-images.githubusercontent.com/97097930/163165791-44f35af9-6974-4a10-b904-b7ae9478b2b4.png">

**Comment by NK-qub** [comment]
> 



> Hi, Are you able to share examples of files that give these errors?

Yes, I try to share the two files here and zip it but i think the size is big so its failed. Any other way to share the files?

**Comment by marksgraham** [comment]
Can you see my email on my profile? Send it to that

**Comment by NK-qub** [comment]
> Can you see my email on my profile? Send it to that

yes sure. I will send it now on your email. Thanks

**Comment by Dbrown411** [comment]
> Thank you for developing this tool. I am using it to convert .e2e format to extract oct images. I have almost 1000 files in .e2e format and trying to extract the oct images from it. However for some of the files it correctly extract the oct images but for few files it gives the following two different errors while extracting oct images. These both errors are for two different .e2e files.
> 1. cannot reshape array of size 366807 into shape (768,768)
> 2. 'int' object has no attribute 'shape'

As Mark mentions in the description, the E2E format was reverse engineered by and adapted from the [uocte project](https://bitbucket.org/uocte/uocte/wiki/Heidelberg%20File%20Format). Considering the hacky nature of the E2E reader, I'd assume without looking too closely at everything that there's a good chance the errors are stemming from scans that are not fully supported. The first error in particular appears to be getting the wrong information from the raw bytes, but i'd also guess the second error could be from a similar issue.

Do you know/have the ability to find out what, if anything, differs between scans that properly export vs those that don't? e.g.
- Do they all come from the same heidelberg device? 
- Were they using the same scan protocols? If not, how specifically do they differ?

If these errors are caused by the incomplete reverse engineering of the filetype, knowing more about the scans themselves would probably be pretty important. But this will probably be difficult and require some trial and error, so would also be happy to lend a hand if files were forwarded along. 

Dillon

**Comment by marksgraham** [comment]
This should be fixed now , can you pull again and check?

@Dbrown411 in this case it looked like genuine bugs in the .e2e reader that were readily addressable, thanfully!

**Comment by NK-qub** [comment]
> This should be fixed now , can you pull again and check?
> 
> @Dbrown411 in this case it looked like genuine bugs in the .e2e reader that were readily addressable, thanfully!

@marksgraham yes, I have pulled the updated code and it works without any errors. Many Thanks!
